version: '3'

services:
    selenium:
        image: selenium/standalone-chrome${SELENIUM_IMAGE_SUFFIX}:2.53.1
        ports:
            - "4444:4444" # http://localhost:4444/wd/hub/static/resource/hub.html
            - "5900:5900" # VNC connection for debug images
        volumes:
            - "/dev/shm:/dev/shm"
            - "./spectrum/templates/:/templates"
